global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'pip-platform'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "prometheus-alerts.yml"

# Scrape configurations
scrape_configs:
  # Payment Integration Platform Application
  - job_name: 'pip-application'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pip-app:8080']
        labels:
          application: 'pip-platform'
          environment: 'production'

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
        labels:
          application: 'postgres'
          environment: 'production'

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          application: 'redis'
          environment: 'production'

  # RabbitMQ Exporter
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
        labels:
          application: 'rabbitmq'
          environment: 'production'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          application: 'prometheus'
          environment: 'production'
